# Generated by Django 6.0.7 on 2026-07-12 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='machine_required',
            new_name='service_required',
        ),
    ]
