# Generated by Django 6.0.7 on 2026-07-12 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_machine_required_lead_service_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='categories',
            new_name='category',
        ),
    ]
