# Generated by Django 6.0.7 on 2026-07-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_categories_business_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
