# Generated by Django 6.0.7 on 2026-07-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_business_status_alter_business_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='category',
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.ManyToManyField(related_name='Businesses', to='app.category'),
        ),
    ]
