# Generated by Django 6.0.7 on 2026-07-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_business_category_business_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='provides',
            field=models.CharField(choices=[('P', 'Pan indai'), ('R', 'Regional')], default='R', max_length=2),
        ),
    ]
