# Generated by Django 6.0.7 on 2026-07-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_business_provides'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='project_caption1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='business',
            name='project_caption2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='business',
            name='project_caption3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='business',
            name='project_caption4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='business',
            name='project_image1',
            field=models.ImageField(blank=True, null=True, upload_to='business/projects/'),
        ),
        migrations.AddField(
            model_name='business',
            name='project_image2',
            field=models.ImageField(blank=True, null=True, upload_to='business/projects/'),
        ),
        migrations.AddField(
            model_name='business',
            name='project_image3',
            field=models.ImageField(blank=True, null=True, upload_to='business/projects/'),
        ),
        migrations.AddField(
            model_name='business',
            name='project_image4',
            field=models.ImageField(blank=True, null=True, upload_to='business/projects/'),
        ),
    ]
