# Generated by Django 6.0.7 on 2026-07-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_business_project_caption1_business_project_caption2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='one_line',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
