# Generated by Django 6.0.7 on 2026-07-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_category_one_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='one_line',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
