# Generated by Django 6.0.7 on 2026-07-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_category_one_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='project_location1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='business',
            name='project_location2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='business',
            name='project_location3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='business',
            name='project_location4',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
