# Generated by Django 6.0.7 on 2026-07-21 10:24

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_business_project_location1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecitypage',
            name='faq',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='FAQ'),
        ),
    ]
